.test:cargo:
  stage: test
  cache:
    key: "${CI_COMMIT_REF_SLUG}-${CI_RUNNER_ID}"
    paths:
      - target/
  tags:
    - ipfs
    - linux
    - bigbox
  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo test

deploy_review:
  stage: deploy
  cache:
    key: "${CI_COMMIT_REF_SLUG}-${CI_RUNNER_ID}"
    paths:
      - target/
  tags:
    - ipfs
    - linux
    - bigbox
  artifacts:
    reports:
      dotenv: deploy.env
  environment:
    name: review/$CI_COMMIT_REF_SLUG
    url: $DYNAMIC_ENVIRONMENT_URL
  only:
    - merge_requests

  script:
    - LATEST=$(ipfs resolve /ipns/mm.em32.net)
    - mkdir S01
    - mkdir S02
    - ipfs cat $LATEST/S01/metadata.json > S01/metadata.json
    - ipfs cat $LATEST/S02/metadata.json > S02/metadata.json
    - env RUST_BACKTRACE=1 cargo run -- -i data/_Season01.json -o deploy_output/S01 -m S01/metadata.json
    - env RUST_BACKTRACE=1 cargo run -- -i data/_Season02.json -o deploy_output/S02 -m S02/metadata.json
    - env RUST_BACKTRACE=1 cargo run -- --patch --hash=$LATEST -o deploy_output/ | tee patch.log
    - NEW=$(cat patch.log |tail -1)
    - DWEB=$(ipfs cid format -v1 $NEW -bbase32)
    - printf "DYNAMIC_ENVIRONMENT_URL=https://${DWEB}.ipfs.dweb.link/" > deploy.env
